# Change these first
owner: goodvat # Your GitHub organization or username, where this repository lives
repo: goodvat-status # The name of this repository

secrets:
  - GOODVAT_API_KEY

sites:
  - name: GoodVAT API Health
    slug: good-vat-api-health
    url: https://api.goodvat.com/health
    expectedStatusCodes:
      - 200

  - name: GoodVAT Address Normalization
    slug: good-vat-api
    url: https://api.goodvat.com/v1/address/normalize
    method: POST
    headers:
      - "Authorization: Bearer $GOODVAT_API_KEY"
      - "Content-Type: application/json"
    body: '{"query": "781 Franklin Ave Crown Heights Brooklyn NY 11216 USA", "language": "en", "country": "USA"}'
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.goodvat.com
  # baseUrl: /your-repo-name
  name: GoodVAT Status
  introTitle: "**GoodVAT API** status"
  introMessage: Live status and uptime history for the GoodVAT API.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
